on:
  push:
    branches:
      - main
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.version.outputs.v-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN ${{ steps.version.outputs.version }}"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
